version: "3.9"
services:
  backend:
    restart: always
    build:
      context: ./app
      dockerfile: ./Dockerfile
    container_name: backend_c
    ports:
      - "127.0.0.1:80:80"
    volumes:
      - react_build:/code/build
    stdin_open: true
    tty: true

  frontend:
    build:
      context: ./react-app
      dockerfile: ./Dockerfile
    ports:
      - "127.0.0.1:8000:80"
    volumes:
      - react_build:/app/build


volumes:
   react_build: