version: "3.9"
services:
  backend:
    build:
      context: ./app
      dockerfile: ./Dockerfile
    container_name: backend_c
    ports:
      - "127.0.0.1:80:80"
    stdin_open: true
    tty: true

  frontend:
    build:
      context: ./web
      dockerfile: ./Dockerfile
    restart: always
    ports:
      - "127.0.0.1:3000:3000"
    expose:
      - 3000