version: "3.9"
services:
  backend:
    build:
      context: ./app
      dockerfile: ./Dockerfile
    container_name: backend_c
    ports:
      - "127.0.0.1:80:80"
    volumes:
      - react_build:/code/build
    stdin_open: true
    tty: true

  frontend:
    build:
      context: ./react-app
      dockerfile: ./Dockerfile
    ports:
      - "127.0.0.1:8000:80"
    volumes:
      - react_build:/app/build

  db:
    image: postgres:15
    restart: always
    environment:
      - POSTGRES_PASSWORD=lol
      - POSTGRES_USER=lol
      - POSTGRES_DB=lol
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - 5432:5432

volumes:
   postgres_data:
   react_build: